name: Build Janus Multi-Arch Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v3

      # Set up QEMU for multi-arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Copy certificate files from GitHub secrets to build context
      - name: Prepare Certificates
        run: |
          mkdir -p cert
          echo "${{ secrets.CERT_PEM }}" > cert/combined_certificate.pem
          echo "${{ secrets.CERT_KEY }}" > cert/KeyFile_www.aioceaneye.com_crt.key

      # Build and push multi-arch image
      - name: Build and Push Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t marinedrone/janus:latest \
            --push \
            .
