services:
  janus:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PUBLIC_IP=localhost
    ports:
      - "80:80"
      - "443:443"
      - "8088:8088"
      - "8188:8188"
      - "8989:8989"
      - "5001-5005:5001-5005/udp"
    networks:
      - janus-net

networks:
  janus-net:
    driver: bridge